### ISSUE TITLE
Suggestions before this code gets fully released and compiled for end/power-users

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [palera1n/openra1n#1]
Can we expect something like this but more detailed and maybe official. Just imagine OpenRa1n/Palera1n official windows version with GUI but with more options for example verbose boot, choosing between rootless and rootful and other settings without booting into linux system via USB and without MacBook:

Here's an example of unofficial demo how would looks like the UI and jailbreaking method using Windows (drivers and etc...) but for more settings, you can implement in an official version : )

[https://frpfile.com/palera1n/](https://frpfile.com/palera1n/)

- Just download exe, decompile it and see how it works so you can see what you can do to enable Windows users to have an official version of the tool GUI included

**Comment by eugolonom** [comment]
We know other versions exist and done some research before, but it's not a priority for us.

Avoid making issues like these in the future.
